# Generated by Django 2.2.2 on 2019-06-24 15:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demand_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratDeTravail',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
                ('designation', models.CharField(max_length=20)),
                ('passport', models.ImageField(upload_to='')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='Hebergement',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
                ('location', models.CharField(max_length=50)),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='Immigration',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='PlaneTicket',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
                ('destination', models.CharField(max_length=50)),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('demande', models.CharField(choices=[('hr', 'Réservation Hotel'), ('hbrg', 'Hébergement'), ('vs', 'visa'), ('ct', 'Contrat De Travail'), ('pt', "Billet D'avion"), ('vse', "Visa d'étude"), ('imgr', 'Immigration'), ('cc', 'Credit Card')], default='vs', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
                ('passport', models.ImageField(upload_to='')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.RenameField(
            model_name='demand',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='demand',
            name='first_name',
            field=models.CharField(blank=True, default='khra', max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='demand',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 6, 24, 15, 29, 54, 238647, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VisaEtude',
            fields=[
                ('visa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Visa')),
                ('country', models.CharField(max_length=50)),
            ],
            bases=('demand_handler.visa',),
        ),
    ]
