# Generated by Django 2.2.2 on 2019-06-25 16:17

from django.db import migrations, models
import django.db.models.deletion
import elbiban_tours.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0002_auto_20190624_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hebergement',
            name='country',
            field=models.CharField(default='Canada', max_length=50),
        ),
        migrations.AddField(
            model_name='immigration',
            name='country',
            field=models.CharField(default='Canada', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('vc', 'Visa Card'), ('mc', 'Master Card')], default='vc', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='passport',
            field=models.ImageField(upload_to=elbiban_tours.utilities.upload_image_path),
        ),
        migrations.AlterField(
            model_name='planeticket',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_handler.Voyage'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='demande',
            field=models.CharField(choices=[('cc', 'Credit Card'), ('hr', 'Réservation Hotel'), ('ct', 'Contrat De Travail'), ('imgr', 'Immigration'), ('vse', "Visa d'étude"), ('pt', "Billet D'avion"), ('vs', 'visa'), ('hbrg', 'Hébergement')], default='vs', max_length=15),
        ),
        migrations.AlterField(
            model_name='visa',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to=elbiban_tours.utilities.upload_image_path),
        ),
        migrations.AlterField(
            model_name='visaetude',
            name='country',
            field=models.CharField(default='spain', max_length=50),
        ),
    ]
