# Generated by Django 2.2.2 on 2019-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0003_auto_20190625_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('mc', 'Master Card'), ('vc', 'Visa Card')], default='vc', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='demande',
            field=models.CharField(choices=[('cc', 'Credit Card'), ('pt', "Billet D'avion"), ('ct', 'Contrat De Travail'), ('vs', 'visa'), ('imgr', 'Immigration'), ('hr', 'Réservation Hotel'), ('hbrg', 'Hébergement'), ('vse', "Visa d'étude")], default='vs', max_length=15),
        ),
    ]
