# Generated by Django 2.2.2 on 2019-06-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0006_auto_20190625_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('vc', 'Visa Card'), ('mc', 'Master Card')], default='vc', max_length=20),
        ),
        migrations.AlterField(
            model_name='planeticket',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation_handler.Voyage'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='demande',
            field=models.CharField(choices=[('pt', "Billet D'avion"), ('hr', 'Réservation Hotel'), ('vse', "Visa d'étude"), ('ct', 'Contrat De Travail'), ('vs', 'visa'), ('cc', 'Credit Card'), ('hbrg', 'Hébergement'), ('imgr', 'Immigration')], default='vs', max_length=15),
        ),
    ]
