# Generated by Django 2.2.2 on 2019-06-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_reservationvisa_visaetudereservation'),
        ('demand_handler', '0008_auto_20190626_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='designated_visa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.ReservationVisa'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('mc', 'Master Card'), ('vc', 'Visa Card')], default='vc', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='demande',
            field=models.CharField(choices=[('ct', 'Contrat De Travail'), ('vs', 'visa'), ('vse', "Visa d'étude"), ('pt', "Billet D'avion"), ('cc', 'Credit Card'), ('hr', 'Réservation Hotel'), ('hbrg', 'Hébergement'), ('imgr', 'Immigration')], default='vs', max_length=15),
        ),
    ]
