# Generated by Django 2.2.2 on 2019-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0010_auto_20190726_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visa',
            name='designated_visa',
        ),
        migrations.AddField(
            model_name='visa',
            name='destination',
            field=models.CharField(default='france', max_length=50),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('vc', 'Visa Card'), ('mc', 'Master Card')], default='vc', max_length=20),
        ),
    ]
