# Generated by Django 2.2.2 on 2019-07-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0011_auto_20190730_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('mc', 'Master Card'), ('vc', 'Visa Card')], default='vc', max_length=20),
        ),
    ]
