# Generated by Django 2.2.2 on 2019-07-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0012_auto_20190731_0006'),
    ]

    operations = [
        
    ]
