# Generated by Django 2.2.2 on 2019-08-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0024_auto_20190803_1428'),
        ('demand_handler', '0013_delete_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoyageDemand',
            fields=[
                ('demand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='demand_handler.Demand')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Voyage')),
            ],
            bases=('demand_handler.demand',),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('vc', 'Visa Card'), ('mc', 'Master Card')], default='vc', max_length=20),
        ),
        migrations.AlterField(
            model_name='demand',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='planeticket',
            name='destination',
            field=models.CharField(default='paris', max_length=40),
        ),
    ]
