# Generated by Django 2.2.2 on 2019-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demand_handler', '0014_auto_20190803_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='etat',
            field=models.CharField(choices=[('at', 'En Attente'), ('ec', 'En Cours'), ('rf', 'Refusé'), ('sv', 'Servi')], default='at', max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='designation',
            field=models.CharField(choices=[('mc', 'Master Card'), ('vc', 'Visa Card')], default='vc', max_length=20),
        ),
    ]
