# Generated by Django 2.2.2 on 2019-06-25 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elbiban_tours.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_title_1', models.CharField(max_length=50)),
                ('landing_title_2', models.CharField(max_length=50)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fax_number', models.DecimalField(decimal_places=0, max_digits=9)),
                ('email', models.EmailField(max_length=254)),
                ('agency_description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('facebook_link', models.CharField(max_length=100)),
                ('twitter_link', models.CharField(max_length=100)),
                ('instagram_link', models.CharField(max_length=100)),
                ('msg_confirmation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LandingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=elbiban_tours.utilities.upload_image_path)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('svg', models.FileField(null=True, upload_to=elbiban_tours.utilities.upload_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=elbiban_tours.utilities.upload_image_path)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('client_badge', models.CharField(choices=[('nouveau client', 'nouveau client'), ('client fidèle', 'client fidèle')], default='nouveau client', max_length=20)),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
