# Generated by Django 2.2.2 on 2019-06-25 23:29

from django.db import migrations, models
import elbiban_tours.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=elbiban_tours.utilities.upload_image_path)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
