# Generated by Django 2.2.2 on 2019-06-25 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_voyage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationVisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisaEtudeReservation',
            fields=[
                ('reservationvisa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administration.ReservationVisa')),
                ('country', models.CharField(max_length=50)),
                ('Universty', models.CharField(max_length=50)),
            ],
            bases=('administration.reservationvisa',),
        ),
    ]
