# Generated by Django 2.2.2 on 2019-06-29 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_reservationvisa_visaetudereservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('client fidèle', 'client fidèle'), ('nouveau client', 'nouveau client')], default='nouveau client', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
