# Generated by Django 2.2.2 on 2019-07-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_auto_20190701_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
