# Generated by Django 2.2.2 on 2019-07-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20190701_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('client fidèle', 'client fidèle'), ('nouveau client', 'nouveau client')], default='nouveau client', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('non disponible', 'indisponible'), ('Disponible', 'disponible')], default='Disponible', max_length=20),
        ),
    ]
