# Generated by Django 2.2.2 on 2019-07-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_auto_20190702_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('nouveau client', 'nouveau client'), ('client fidèle', 'client fidèle')], default='nouveau client', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('indisponible', 'indisponible')], default='Disponible', max_length=20),
        ),
    ]
