# Generated by Django 2.2.2 on 2019-07-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_auto_20190702_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_in_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('indisponible', 'indisponible'), ('Disponible', 'disponible')], default='Disponible', max_length=20),
        ),
    ]
