# Generated by Django 2.2.2 on 2019-07-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_auto_20190702_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('indisponible', 'indisponible')], default='Disponible', max_length=20),
        ),
    ]
