# Generated by Django 2.2.2 on 2019-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_auto_20190729_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='has_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('client fidèle', 'client fidèle'), ('nouveau client', 'nouveau client')], default='nouveau client', max_length=20),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('indisponible', 'indisponible'), ('Disponible', 'disponible')], default='Disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='requirements',
            field=models.ManyToManyField(related_name='service', to='administration.Requirement'),
        ),
    ]
