# Generated by Django 2.2.2 on 2019-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_auto_20190729_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('nouveau client', 'nouveau client'), ('client fidèle', 'client fidèle')], default='nouveau client', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='service', to='administration.Requirement'),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('indisponible', 'indisponible')], default='Disponible', max_length=20),
        ),
    ]
