# Generated by Django 2.2.2 on 2019-07-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0015_auto_20190730_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_in_section_1',
            field=models.BooleanField(default=False),
        ),
    ]
