# Generated by Django 2.2.2 on 2019-07-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_newsletter_newslettermember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaetudereservation',
            name='reservationvisa_ptr',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('nouveau client', 'nouveau client'), ('client fidèle', 'client fidèle')], default='nouveau client', max_length=20),
        ),
        migrations.DeleteModel(
            name='ReservationVisa',
        ),
        migrations.DeleteModel(
            name='VisaEtudeReservation',
        ),
    ]
