# Generated by Django 2.2.2 on 2019-08-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0020_auto_20190801_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingimage',
            name='is_for_about',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('client fidèle', 'client fidèle'), ('nouveau client', 'nouveau client')], default='nouveau client', max_length=20),
        ),
    ]
