# Generated by Django 2.2.2 on 2019-08-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0021_auto_20190801_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='dure',
            field=models.CharField(default='15 jours', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='client_badge',
            field=models.CharField(choices=[('nouveau client', 'nouveau client'), ('client fidèle', 'client fidèle')], default='nouveau client', max_length=20),
        ),
    ]
