# Generated by Django 2.2.2 on 2019-08-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0022_auto_20190803_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('indisponible', 'indisponible'), ('Disponible', 'disponible')], default='Disponible', max_length=20),
        ),
    ]
