# Generated by Django 2.2.2 on 2019-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0023_auto_20190803_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='availability',
            field=models.CharField(choices=[('Disponible', 'disponible'), ('indisponible', 'indisponible')], default='Disponible', max_length=20),
        ),
    ]
